// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRHEjUWkXMJNRm6_HSTWoAa0Itn17ujs',
    appId: '1:41265234984:web:a475249464414250ea611d',
    messagingSenderId: '41265234984',
    projectId: 'timesheetovertime',
    authDomain: 'timesheetovertime.firebaseapp.com',
    storageBucket: 'timesheetovertime.appspot.com',
    measurementId: 'G-CB5S45X3NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJLgE1rib29cZeGDfKP1r3Ly1LNiT-vSg',
    appId: '1:41265234984:android:bb6cba58ccc785a3ea611d',
    messagingSenderId: '41265234984',
    projectId: 'timesheetovertime',
    storageBucket: 'timesheetovertime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEeH3w93RzJCoQrkbfx2qDlEFExGJVxQE',
    appId: '1:41265234984:ios:0c5e3862303f4c45ea611d',
    messagingSenderId: '41265234984',
    projectId: 'timesheetovertime',
    storageBucket: 'timesheetovertime.appspot.com',
    iosClientId: '41265234984-5id9histbj1ptmp8p6fahv51to96gd0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.timesheetOvertime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEeH3w93RzJCoQrkbfx2qDlEFExGJVxQE',
    appId: '1:41265234984:ios:0c5e3862303f4c45ea611d',
    messagingSenderId: '41265234984',
    projectId: 'timesheetovertime',
    storageBucket: 'timesheetovertime.appspot.com',
    iosClientId: '41265234984-5id9histbj1ptmp8p6fahv51to96gd0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.timesheetOvertime',
  );
}
